### Get launches

GET http://localhost:4000/v1/launches

### Get planets

GET http://localhost:4000/v1/planets

### add new launch
POST http://localhost:4000/v1/launches HTTP/1.1
content-type: application/json

{
    "mission": "Kepler Expedition XI",
    "rocket": "Explorer IS1",
    "launchDate": "Jan 31, 2037",
    "target": "Kepler-442 h"
}

### add new launch missing rocket name
POST http://localhost:4000/v1/launches HTTP/1.1
content-type: application/json

{
    "mission": "Kepler Expedition XI",
    "rocket": "",
    "launchDate": "Jan 31, 2037",
    "target": "Kepler-442 h"
}

### add new launch wrong launch date
POST http://localhost:4000/v1/launches HTTP/1.1
content-type: application/json

{
    "mission": "Kepler Expedition XI",
    "rocket": "Explorer IS1",
    "launchDate": "keke",
    "target": "Kepler-442 h"
}

### delete launch 
DELETE http://localhost:4000/v1/launches/100 HTTP/1.1

### delete launch wrong id
DELETE http://localhost:4000/v1/launches/10 HTTP/1.1

